steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/giftmybook-children-worker', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/giftmybook-children-worker']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - giftmybook-children-worker
      - --image=gcr.io/$PROJECT_ID/giftmybook-children-worker
      - --region=europe-west1
      - --platform=managed
      - --no-cpu-throttling
      - --cpu=4
      - --memory=8Gi
      - --concurrency=1
      - --timeout=3600
      - --min-instances=1
      - --max-instances=20
      - --execution-environment=gen2
      - --cpu-boost
      - --no-allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/giftmybook-children-worker'
