/**
 * Hero-prop sprite pipeline.
 *
 * Previously this shelled out to Meshy.ai for text-to-3D GLB models. After
 * the 2.5D pivot the game is all billboarded sprites, so a hero prop is now
 * a single transparent PNG generated by Gemini in the shared Don't Starve
 * painterly style.
 *
 * Output entry shape (persisted on `ChildrenBook.gameHeroPropsJson.props`):
 *   {
 *     id,            // stable per-prop id used by the client registry
 *     itemId,        // hook into itemRegistry.js when the prop adopts a
 *                    // known id (apple, teddy, …) — otherwise null
 *     roomId,        // optional room filter
 *     name,          // display name
 *     url,           // transparent PNG on GCS
 *     width,         // source px, lets the client reserve billboard size
 *     height,
 *     interaction,   // optional override that the client layers onto the
 *                    // base itemInteractions entry
 *   }
 */

const { uploadBuffer } = require('./gcsStorage');
const { generateSpritePng } = require('./gameSpriteCore');
const { spritePrompt } = require('./spriteStyle');

function resolveRefs({ characterRefUrl, coverImageUrl }) {
  const refs = [];
  if (characterRefUrl) refs.push({ url: characterRefUrl, label: 'BOOK ART STYLE (match colour + line weight):' });
  if (coverImageUrl && refs.length < 2) refs.push({ url: coverImageUrl, label: 'BOOK COVER (style only):' });
  return refs;
}

function buildHeroPrompt(prop) {
  const subject = prop.prompt
    ? `Draw a single children's-book hero prop: ${prop.prompt}.`
    : `Draw a single children's-book hero prop: a ${prop.name || prop.id}.`;
  const extra = [
    'SUBJECT RULES:',
    `- The subject is exactly "${prop.name || prop.id}" — nothing else in frame, no child, no hand, no environment.`,
    '- Friendly child-safe design, rounded corners, no sharp blades or scary detailing.',
    '- If the prop could be "on" or "off" (lamp / candle), render it in its neutral / off state.',
  ];
  return spritePrompt(subject, extra);
}

/**
 * Generate a single hero sprite and upload it to GCS.
 *
 * @param {{ bookId, prop, characterRefUrl?, coverImageUrl? }} input
 */
async function generateHeroProp({ bookId, prop, characterRefUrl, coverImageUrl }) {
  if (!bookId) throw new Error('bookId required');
  if (!prop || !prop.id) throw new Error('prop { id } required');

  const slug = prop.id.replace(/[^a-z0-9_-]+/gi, '_').toLowerCase();
  const prompt = buildHeroPrompt(prop);
  const refs = resolveRefs({ characterRefUrl, coverImageUrl });

  const { buffer, width, height } = await generateSpritePng({ prompt, refs, aspectRatio: '1:1' });
  const url = await uploadBuffer(
    buffer,
    `game-hero-props/${bookId}/${slug}.png`,
    'image/png',
  );

  return {
    id: prop.id,
    itemId: prop.itemId || null,
    roomId: prop.roomId || null,
    name: prop.name || prop.id,
    url,
    width,
    height,
    interaction: prop.interaction || null,
  };
}

/**
 * Generate a list of hero props in series (one Gemini call each — keeps us
 * well under concurrency limits and lets partial failures surface cleanly).
 */
async function generateHeroProps({ bookId, props, characterRefUrl, coverImageUrl }) {
  if (!Array.isArray(props) || props.length === 0) {
    return { props: [], partialFailures: [] };
  }
  const generated = [];
  const partialFailures = [];
  for (const p of props) {
    try {
      const out = await generateHeroProp({ bookId, prop: p, characterRefUrl, coverImageUrl });
      generated.push(out);
    } catch (e) {
      console.warn(`[heroProps] ${p.id} failed: ${e.message}`);
      partialFailures.push({ id: p.id, error: e.message });
    }
  }
  return { props: generated, partialFailures };
}

module.exports = { generateHeroProp, generateHeroProps };
