/**
 * Worker Commits — exposes the last 3 git commits baked into the image.
 *
 * `commits.json` is generated by `scripts/captureCommits.js` during CI
 * (see .github/workflows/deploy.yml) and ships inside the Docker build
 * context. This module reads it once at startup and returns a compact
 * payload suitable for attaching to progress/completion callbacks so the
 * admin monitor can show "what was fixed in the worker version that
 * generated this book".
 */

const fs = require('fs');
const path = require('path');

const COMMITS_PATH = path.resolve(__dirname, '..', 'commits.json');

let cached = null;

/**
 * Load commits.json from disk. Returns `null` if the file is missing or
 * malformed so callers can fall back to "unknown" without crashing.
 */
function loadCommits() {
  if (cached !== null) return cached;
  try {
    if (!fs.existsSync(COMMITS_PATH)) {
      cached = [];
      return cached;
    }
    const raw = fs.readFileSync(COMMITS_PATH, 'utf8');
    const parsed = JSON.parse(raw);
    const commits = Array.isArray(parsed?.commits) ? parsed.commits : [];
    cached = commits
      .filter(c => c && typeof c === 'object' && c.subject)
      .slice(0, 3)
      .map(c => ({
        sha: c.sha || null,
        shortSha: c.shortSha || (c.sha ? c.sha.slice(0, 7) : null),
        subject: String(c.subject).slice(0, 200),
        author: c.author || null,
        authorDate: c.authorDate || null,
      }));
  } catch (err) {
    console.warn(`[workerCommits] Failed to read ${COMMITS_PATH}: ${err.message}`);
    cached = [];
  }
  return cached;
}

/**
 * Returns the last 3 commits (most-recent first) as a JSON-serializable array.
 * Empty array if no commits.json was shipped with the image.
 */
function getWorkerCommits() {
  return loadCommits();
}

module.exports = { getWorkerCommits };
