/**
 * Music suites — one per theme, elected once (ab-1, docs/AUDIOBOOK_V2_PLAN.md
 * §4.5). Nine cues from FIXED prompts (the theme's instrument palette +
 * the world-law card's palette line + the cue's mood line), generated by
 * the music provider, N candidates judged by ONE Gemini audio call each
 * (closed fields) and measured, the best elected create-if-absent under
 * `catalog-assets/music-suites/{AUDIO_VERSION}/{themeId}-{promptHash}/`.
 * A cue that cannot be elected falls open to the CC0 library file with an
 * advisory — the words never wait for the music.
 */

const fs = require('fs');
const path = require('path');
const { AUDIO_VERSION } = require('../../versions');
const { getWorldCard } = require('../../worldCards');
const { judgeAudio } = require('../geminiAudio');
const { electAsset, promptHash } = require('../assets');
const { CUES, MOTIF_CUE } = require('./plan');
const { resolveMusicProvider } = require('./providers');
const flags = require('../../flags');

const PALETTES_PATH = path.join(__dirname, '..', '..', 'data', 'audio', 'musicPalettes.json');
const FALLBACK_DIR = path.join(__dirname, '..', '..', 'data', 'audio', 'fallback');
const SUITE_CUES = [...CUES, MOTIF_CUE];
let _palettes = null;

/** @returns {object} the palettes file */
function loadPalettes() {
  if (!_palettes) _palettes = JSON.parse(fs.readFileSync(PALETTES_PATH, 'utf8'));
  return _palettes;
}

/**
 * The fixed prompt of one cue for one theme.
 * @param {{theme_id?: string, themeId?: string, display_name?: string, world_name?: string}} theme
 * @param {string} cueId
 * @returns {{prompt: string, negative: string, seconds: number}}
 */
function cuePrompt(theme, cueId) {
  const p = loadPalettes();
  const themeId = theme.theme_id || theme.themeId;
  const pal = p.themes[themeId] || { instruments: 'warm piano, soft strings', tempoBpm: 80, key: 'C major', feel: 'gentle' };
  const cue = p.cues[cueId];
  if (!cue) throw new Error(`unknown music cue ${cueId}`);
  const card = getWorldCard(themeId);
  const paletteLine = Array.isArray(card) ? (card.find(l => /^Palette/i.test(l)) || '') : '';
  const prompt = [
    `${p.global.style}.`,
    `Instruments: ${pal.instruments}. Tempo ${pal.tempoBpm} bpm, key of ${pal.key}. Feel: ${pal.feel}.`,
    paletteLine ? `The world: ${paletteLine}` : '',
    `This cue: ${cue.mood}.`,
    cueId === MOTIF_CUE ? 'Four seconds only.' : `About ${cue.seconds} seconds.`,
  ].filter(Boolean).join(' ');
  return { prompt, negative: p.global.negative, seconds: cue.seconds };
}

/**
 * The suite's prompt hash — every cue prompt + the version (a palette or
 * world-card edit elects a new suite).
 * @param {object} theme
 * @returns {string}
 */
function suiteHash(theme) {
  return promptHash(`${AUDIO_VERSION}|${SUITE_CUES.map(c => cuePrompt(theme, c).prompt).join('|')}`);
}

/** @param {object} theme @returns {string} */
function suiteBase(theme) {
  return `catalog-assets/music-suites/${AUDIO_VERSION}/${theme.theme_id || theme.themeId}-${suiteHash(theme)}`;
}

const MUSIC_JUDGE_SCHEMA = {
  type: 'OBJECT',
  properties: {
    has_vocals: { type: 'BOOLEAN' }, heavy_percussion: { type: 'BOOLEAN' }, harsh_or_loud_hits: { type: 'BOOLEAN' },
    mood_match: { type: 'INTEGER' }, abrupt_ending: { type: 'BOOLEAN' }, quality: { type: 'INTEGER' },
  },
  required: ['has_vocals', 'heavy_percussion', 'harsh_or_loud_hits', 'mood_match', 'abrupt_ending', 'quality'],
};

/**
 * Judge one candidate cue. Fail-open: an outage yields an unchecked verdict.
 * @param {{buffer: Buffer, mimeType: string}} cand
 * @param {string} mood
 * @param {object} [costTracker]
 * @param {AbortSignal} [signal]
 * @returns {Promise<{ok: boolean, score: number, verdict: object|null, unchecked: string|null}>}
 */
async function judgeCue(cand, mood, costTracker, signal) {
  try {
    const { json } = await judgeAudio({
      prompt: `You are checking one candidate music cue for a children's audiobook score. It must be INSTRUMENTAL (no vocals, no lyrics), gentle (no heavy drums, no harsh or loud hits), and match this mood: "${mood}". Rate mood_match 1-5 and quality 1-5 (composition + audio cleanliness). abrupt_ending is true when the cue stops without resolving. Return JSON only.`,
      audio: [{ buffer: cand.buffer, mimeType: cand.mimeType }], schema: MUSIC_JUDGE_SCHEMA, costTracker, signal, maxOutputTokens: 512,
    });
    const mood_match = Number(json.mood_match) || 0;
    const quality = Number(json.quality) || 0;
    const ok = json.has_vocals !== true && json.heavy_percussion !== true && json.harsh_or_loud_hits !== true && mood_match >= 3;
    return { ok, score: quality * 10 + mood_match * 8 - (json.abrupt_ending ? 15 : 0), verdict: { ...json, mood_match, quality }, unchecked: null };
  } catch (err) {
    return { ok: true, score: 0, verdict: null, unchecked: err.message };
  }
}

/**
 * The CC0 library fallback for a cue.
 * @param {string} cueId
 * @returns {{path: string, fallback: true, cueId: string}|null}
 */
function fallbackCue(cueId) {
  const p = loadPalettes();
  const file = p.fallback && p.fallback.byCue && p.fallback.byCue[cueId];
  if (!file) return null;
  const full = path.join(FALLBACK_DIR, file);
  return fs.existsSync(full) ? { path: full, fallback: true, cueId, mimeType: 'audio/mpeg' } : null;
}

/**
 * Elect (or fetch) one theme's suite.
 * @param {object} p
 * @param {object} p.theme
 * @param {string[]} [p.cueIds] the cues the book needs (default: all nine)
 * @param {object} [p.costTracker]
 * @param {(level: string, msg: string) => void} [p.log]
 * @param {AbortSignal} [p.signal]
 * @param {object} [p.credentials]
 * @returns {Promise<{themeId: string, hash: string, provider: string|null, cues: Object<string, object>, fallbackCues: string[], advisories: object[]}>}
 */
async function getMusicSuite({ theme, cueIds = SUITE_CUES, costTracker, log = () => {}, signal, credentials = {} }) {
  const themeId = theme.theme_id || theme.themeId;
  const hash = suiteHash(theme);
  const base = suiteBase(theme);
  const cues = {};
  const fallbackCues = [];
  const advisories = [];
  const resolved = flags.audioMusicEnabled() ? resolveMusicProvider() : { ok: false, error: 'music disabled' };
  const n = flags.audioAssetCandidates();
  for (const cueId of cueIds) {
    const { prompt, negative, seconds } = cuePrompt(theme, cueId);
    let record = null;
    if (resolved.ok && resolved.provider !== 'library') {
      const r = await electAsset({
        recordKey: `${base}/${cueId}.json`,
        bytesKeyBase: `${base}/${cueId}`,
        log,
        produce: async () => {
          const cands = [];
          for (let k = 1; k <= n; k++) {
            try {
              const g = await resolved.adapter.generate({ prompt, negativePrompt: negative, seconds, seed: k, credentials, signal });
              if (costTracker && typeof costTracker.addAudioSeconds === 'function') costTracker.addAudioSeconds(`${resolved.provider}:${g.model}`, seconds);
              const j = await judgeCue(g, loadPalettes().cues[cueId].mood, costTracker, signal);
              cands.push({ ...g, k, judged: j });
            } catch (err) {
              log('warn', `suite ${themeId}/${cueId}: candidate ${k} failed (${err.message})`);
              if (err.failureCode === 'audiobook_provider_unavailable') throw err;
            }
          }
          const ok = cands.filter(c => c.judged.ok).sort((a, b) => b.judged.score - a.judged.score);
          const best = ok[0];
          if (!best) return null;
          return { buffer: best.buffer, mimeType: best.mimeType, meta: { cueId, themeId, seconds, provider: resolved.provider, model: best.model, prompt, verdict: best.judged.verdict, unchecked: best.judged.unchecked, candidates: cands.length } };
        },
      });
      record = r.record;
    }
    if (!record) {
      const fb = fallbackCue(cueId);
      if (fb) {
        cues[cueId] = fb;
        fallbackCues.push(cueId);
        advisories.push({ stage: 'music', note: `cue ${cueId} of theme ${themeId} uses the CC0 library file (${resolved.ok ? 'no candidate could be elected' : resolved.error})` });
      } else {
        advisories.push({ stage: 'music', note: `cue ${cueId} of theme ${themeId} is unavailable` });
      }
      continue;
    }
    cues[cueId] = { ...record, fallback: false };
  }
  return { themeId, hash, provider: resolved.ok ? resolved.provider : null, cues, fallbackCues, advisories };
}

module.exports = { SUITE_CUES, MUSIC_JUDGE_SCHEMA, loadPalettes, cuePrompt, suiteHash, suiteBase, judgeCue, fallbackCue, getMusicSuite, PALETTES_PATH, FALLBACK_DIR };
