/**
 * The sound library's audio — elected once per cue (ab-1,
 * docs/AUDIOBOOK_V2_PLAN.md §4.6). Every cue in data/audio/sfxCues.json has
 * a FIXED prompt; its audio is generated by the sound provider, N
 * candidates judged (closed fields) and elected create-if-absent under
 * `catalog-assets/sfx/{AUDIO_VERSION}/{cueId}-{promptHash}.…`. A cue that
 * cannot be elected is SKIPPED with an advisory — the words never wait for
 * a sound.
 */

const { AUDIO_VERSION } = require('../../versions');
const { judgeAudio } = require('../geminiAudio');
const { electAsset, promptHash } = require('../assets');
const { loadSfxLibrary } = require('./plan');
const { resolveSfxProvider } = require('./providers');
const flags = require('../../flags');

const SFX_JUDGE_SCHEMA = {
  type: 'OBJECT',
  properties: { matches_description: { type: 'BOOLEAN' }, contains_voice_or_music: { type: 'BOOLEAN' }, harsh_or_startling: { type: 'BOOLEAN' }, quality: { type: 'INTEGER' } },
  required: ['matches_description', 'contains_voice_or_music', 'harsh_or_startling', 'quality'],
};

/** @param {string} cueId @returns {object|null} the cue definition (spot, ambience or page turn) */
function cueDefinition(cueId) {
  const lib = loadSfxLibrary();
  if (lib.byId.has(cueId)) return lib.byId.get(cueId);
  for (const amb of Object.values(lib.ambience)) if (amb.cueId === cueId) return { ...amb, category: 'ambience', startle: false };
  if (lib.pageTurn && lib.pageTurn.cueId === cueId) return { ...lib.pageTurn, category: 'transition', startle: false };
  return null;
}

/** @param {object} cue @returns {string} */
function cueKeyBase(cue) {
  return `catalog-assets/sfx/${AUDIO_VERSION}/${cue.cueId}-${promptHash(`${AUDIO_VERSION}|${cue.prompt}`)}`;
}

/**
 * Judge one candidate sound. Fail-open on an outage.
 * @param {{buffer: Buffer, mimeType: string}} cand
 * @param {object} cue
 * @param {object} [costTracker]
 * @param {AbortSignal} [signal]
 * @returns {Promise<{ok: boolean, score: number, verdict: object|null, unchecked: string|null}>}
 */
async function judgeSound(cand, cue, costTracker, signal) {
  try {
    const { json } = await judgeAudio({
      prompt: `You are checking one candidate sound effect for a children's audiobook. The description it must match: "${cue.prompt}". It must contain NO spoken words, NO singing and NO music melody${cue.category === 'ambience' ? ' (a gentle ambience bed)' : ''}. harsh_or_startling is true when a child could be startled by it (a sudden loud hit, a scream, a harsh noise). Rate quality 1-5. Return JSON only.`,
      audio: [{ buffer: cand.buffer, mimeType: cand.mimeType }], schema: SFX_JUDGE_SCHEMA, costTracker, signal, maxOutputTokens: 256,
    });
    const quality = Number(json.quality) || 0;
    const ok = json.matches_description === true && json.contains_voice_or_music !== true && (cue.startle ? true : json.harsh_or_startling !== true);
    return { ok, score: quality * 10 - (json.harsh_or_startling ? 10 : 0), verdict: { ...json, quality }, unchecked: null };
  } catch (err) {
    return { ok: true, score: 0, verdict: null, unchecked: err.message };
  }
}

/**
 * Elect (or fetch) the audio of the cues a book needs.
 * @param {object} p
 * @param {string[]} p.cueIds
 * @param {object} [p.costTracker]
 * @param {(level: string, msg: string) => void} [p.log]
 * @param {AbortSignal} [p.signal]
 * @param {object} [p.credentials]
 * @returns {Promise<{hash: string, provider: string|null, cues: Object<string, object>, skipped: Array<{cueId: string, reason: string}>, advisories: object[]}>}
 */
async function getSoundCues({ cueIds, costTracker, log = () => {}, signal, credentials = {} }) {
  const lib = loadSfxLibrary();
  const cues = {};
  const skipped = [];
  const advisories = [];
  const resolved = flags.audioSfxEnabled() ? resolveSfxProvider() : { ok: false, error: 'sound effects disabled' };
  const n = flags.audioAssetCandidates();
  for (const cueId of [...new Set(cueIds)]) {
    const cue = cueDefinition(cueId);
    if (!cue) { skipped.push({ cueId, reason: 'unknown cue' }); continue; }
    if (!resolved.ok || resolved.provider === 'library') { skipped.push({ cueId, reason: resolved.ok ? 'no generator' : resolved.error }); continue; }
    const base = cueKeyBase(cue);
    const r = await electAsset({
      recordKey: `${base}.json`,
      bytesKeyBase: base,
      log,
      produce: async () => {
        const cands = [];
        for (let k = 1; k <= n; k++) {
          try {
            const g = await resolved.adapter.generate({ prompt: cue.prompt, seconds: cue.seconds, seed: k, credentials, signal });
            if (costTracker && typeof costTracker.addAudioSeconds === 'function') costTracker.addAudioSeconds(`${resolved.provider}:${g.model}`, cue.seconds);
            cands.push({ ...g, k, judged: await judgeSound(g, cue, costTracker, signal) });
          } catch (err) {
            log('warn', `sound ${cueId}: candidate ${k} failed (${err.message})`);
            if (err.failureCode === 'audiobook_provider_unavailable') throw err;
          }
        }
        const best = cands.filter(c => c.judged.ok).sort((a, b) => b.judged.score - a.judged.score)[0];
        if (!best) return null;
        return { buffer: best.buffer, mimeType: best.mimeType, meta: { cueId, seconds: cue.seconds, category: cue.category, provider: resolved.provider, model: best.model, prompt: cue.prompt, verdict: best.judged.verdict, unchecked: best.judged.unchecked, candidates: cands.length } };
      },
    });
    if (r.record) cues[cueId] = r.record;
    else { skipped.push({ cueId, reason: 'no candidate could be elected' }); advisories.push({ stage: 'sfx', note: `sound cue ${cueId} could not be elected — skipped` }); }
  }
  return { hash: lib.hash, provider: resolved.ok ? resolved.provider : null, cues, skipped, advisories };
}

module.exports = { SFX_JUDGE_SCHEMA, cueDefinition, cueKeyBase, judgeSound, getSoundCues };
